#!/bin/bash

# Variables needed by the server.
echo DIVELOG_MODE="${DIVELOG_MODE}"
echo DIVELOG_WATCH_DIR_PATH="${DIVELOG_WATCH_DIR_PATH}"
echo DIVELOG_IP_HOST="${DIVELOG_IP_HOST}"
echo DIVELOG_PORT="${DIVELOG_PORT}"
echo DIVELOG_PRIVATE_KEY_PATH="${DIVELOG_PRIVATE_KEY_PATH}"
echo DIVELOG_CERT_PATH="${DIVELOG_CERT_PATH}"

# Variables needed by satellite processes.
echo DIVELOG_LOCAL_BACKUP_DIR="${DIVELOG_LOCAL_BACKUP_DIR}"
echo DIVELOG_SSH_LOGIN_TARGET="${DIVELOG_SSH_LOGIN_TARGET}"
echo DIVELOG_HOST_STORE_DIR="${DIVELOG_HOST_STORE_DIR}"
